services:

  postgresql:
    container_name: postgresql
    image: postgres:16.2
    environment:
      POSTGRES_USER: ntloc
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ntloc -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgresql
    restart: always

  spring-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/mydb
      SPRING_DATASOURCE_USERNAME: ntloc
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - postgresql
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always


volumes:
  postgresql:
  pgadmin:


networks:
  postgresql: